- name: Create jenkins container
  hosts: localhost
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
  - name: jenkins container
    docker_container:
     name: jenkins_container
     image: jenkins
     state: started
     ports:
     - "82:80"
     tty: true
     detach: true
