- name: Create wordpress container
  hosts: localhost
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
  tasks:
  - name: wordpress container
    docker_container:
     name: wordpress_container
     image: wordpress
     state: started
     ports:
     - "8888:80"
     tty: true
     detach: true
