- name: Pull Jenkins image
  hosts: localhost
  connection: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}" 
  tasks:
  - name: pull
    docker_image:
      name: jenkins
